# https://github.com/atom/atom/tree/master/packages/one-dark-syntax
# special
background=#282c34
foreground=#abb2bf
cursor=#abb2bf
# black
color0=#5c6370
color8=#666666
# red
color1=#e06c75
color9=#d54e53
# green
color2=#98c379
color10=#b9ca4a
# yellow
color3=#e5c07b
color11=#e7c547
# blue
color4=#61afef
color12=#7aa6da
# magenta
color5=#c678dd
color13=#c397d8
# cyan
color6=#56b6c2
color14=#70c0b1
# white
color7=#828997
color15=#eaeaea
